DFWeb/Controllers/PhanQuyen/PhanQuyenController.cs
using DF.DataAccess;
using DF.DBMapping.Models;
using DF.DBMapping.ModelsExt.PhanQuyen;
using DFWeb.Common;
using DFWeb.Models;
using DFWeb.Security;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace DFWeb.Controllers
{
    public class PhanQuyenController : Controller
    {
        //
        // GET: /PhanQuyen/
        protected UnitOfWork unitofwork;

        [CustomAuthorize(Roles = "2022")]
        public ActionResult Index()
        {

            ViewBag.Title_Function = Models.Language.GetText("phanquyenchucnang");
            return View();
        }

        public JsonResult getDanhSachNhanVien()
        {
            unitofwork = new UnitOfWork();
            try
            {
                var objlist = (from a in unitofwork.Context.NhanViens
                               join b in unitofwork.Context.Users on a.NhanVienID equals b.NhanVienId
                               where a.IsActive == true
                               select new
                               {
                                   UserId = b.UserId,
                                   NhanVienID = a.NhanVienID,
                                   TenNhanVien = a.TenNhanVien,
                                   UserName = b.UserName,
                                   //CMT = a.Cmt,
                                   DiaChi = a.DiaChi,
                                   MatKhau = b.Password
                               }).ToList();
                return Json(new { code = "success", data = objlist, total = objlist.Count }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = "error", message = Models.Language.GetText("mgs_coloitrongquatrinhlaydulieu") }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult genPhanQuyen(string userid)
        {
            List<PhanQuyenModel> lst = new List<PhanQuyenModel>();
            unitofwork = new UnitOfWork();
            try
            {
                Guid IDUser = Guid.Parse(userid);
                var objgroup = (from a in unitofwork.Context.tblGroups
                                select new
                                {
                                    TenQuyen = a.GroupName,
                                    GroupGuid = a.GroupGuid
                                }).OrderBy(z => z.TenQuyen).ToList();
                foreach (var item in objgroup)
                {
                    if ((from a in unitofwork.Context.tblGroupUsers where a.UserGuid == IDUser && a.GroupGuid == item.GroupGuid select a.GroupGuid).ToList().Count > 0)
                    {
                        lst.Add(new PhanQuyenModel
                        {
                            GroupGuid = item.GroupGuid,
                            IsActive = true,
                            TenGroup = item.TenQuyen,
                            UserID = IDUser
                        });
                        continue;
                    }

                    lst.Add(new PhanQuyenModel
                    {
                        GroupGuid = item.GroupGuid,
                        IsActive = false,
                        TenGroup = item.TenQuyen,
                        UserID = IDUser
                    });

                }
                return Json(new { code = "success", message = Models.Language.GetText("mgs_laydulieuthanhcong"), data = lst, total = lst.Count }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new { code = "error", message = Models.Language.GetText("mgs_coloitrongquatrinhlaydulieu") }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult savePhanQuyen(string data, string userid)
        {
            unitofwork = new UnitOfWork();
            List<savePhanQuyenModel> lst = JsonConvert.DeserializeObject<List<savePhanQuyenModel>>(data);
            try
            {
                using (TransactionScope tran = new TransactionScope())
                {
                    unitofwork.tblGroupUsers.delPhanQuyen(userid);
                    foreach (var item in lst)
                    {
                        tblGroupUser gr = new tblGroupUser();
                        gr.GroupGuid = Guid.Parse(item.id);
                        gr.UserGuid = Guid.Parse(userid);
                        unitofwork.tblGroupUsers.Add(gr);
                    }
                    unitofwork.Save();
                    tran.Complete();
                }
                return Json(new { code = "success", message = Models.Language.GetText("mgs_capnhatdulieuthanhcong") }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = "error", message = Models.Language.GetText("thatbai") }, JsonRequestBehavior.AllowGet);
            }
            
        }

        //[CustomAuthorize(Roles = "99999")]
        public ActionResult DanhMucPhanQuyen()
        {
            List<PhanQuyenDanhMucModels> grlist = new List<PhanQuyenDanhMucModels>();
            grlist = lstDM(2);
            return View(grlist);
        }

        public ActionResult SearchDM(int LoaiHinh)
        {
            List<PhanQuyenDanhMucModels> grlist = new List<PhanQuyenDanhMucModels>();
            grlist = lstDM(LoaiHinh);
            return PartialView("~/Views/QLLuongKhoanNhanVien/_DanhMucPhanQuyen.cshtml", grlist);
        }

        public JsonResult GETDMPhanQuyen(int LoaiHinh)
        {

            try
            {
                List<PhanQuyenDanhMucModels> grlist = new List<PhanQuyenDanhMucModels>();
                grlist = lstDM(LoaiHinh);
                return Json(new { code = "success", data = grlist, total = grlist.Count }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = "error", message = Models.Language.GetText("mgs_coloitrongquatrinhlaydulieu") }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult DSQuyenParent()
        {
            unitofwork = new UnitOfWork();
            try
            {
                var grlist = unitofwork.tblGroupUsers.GetDMPhanQuyenParent();
                return Json(new { code = "success", data = grlist, total = grlist.Count }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = "error", message = Models.Language.GetText("mgs_coloitrongquatrinhlaydulieu") }, JsonRequestBehavior.AllowGet);
            }
        }

        public List<PhanQuyenDanhMucModels> lstDM(int LoaiHinh)
        {
            unitofwork = new UnitOfWork();
            List<DF.DataAccess.DBML.Web_PhanQuyen_GetDanhMucPhanQuyenResult> lst = new List<DF.DataAccess.DBML.Web_PhanQuyen_GetDanhMucPhanQuyenResult>();
            List<DF.DataAccess.DBML.Web_PhanQuyen_GetDanhMucPhanQuyenResult> lst2 = new List<DF.DataAccess.DBML.Web_PhanQuyen_GetDanhMucPhanQuyenResult>();
            List<PhanQuyenDanhMucModels> grlist = new List<PhanQuyenDanhMucModels>();
            List<PhanQuyenDanhMucModels> grlistHeader = new List<PhanQuyenDanhMucModels>();
            lst = unitofwork.tblGroupUsers.GetDanhMucPhanQuyen(LoaiHinh);
            lst2 = lst.Where(z => z.IsHeader == true).OrderBy(z => z.Nhom).ToList();
            int icountHeader = 1;
            if (LoaiHinh == 2) // Nếu là web thì load theo phân cấp như thế này
            {
                foreach (var item in lst2)
                {
                    grlist.Add(new PhanQuyenDanhMucModels
                    {
                        Code = item.Code,
                        GroupGuid = item.GroupGuid,
                        GroupName = item.GroupName,
                        GroupParent = item.GroupParent,
                        Icon = item.Icon,
                        IsHeader = item.IsHeader,
                        KeyLanguage = item.KeyLanguage,
                        LoaiHinh = item.LoaiHinh,
                        MoTa = item.MoTa,
                        Nhom = item.Nhom,
                        RuleType = item.RuleType,
                        UrlLink = item.UrlLink,
                        STT = Utils.Utils.GetSoLaMa(icountHeader.ToString(), true),
                        STT2 = item.STT
                    });
                    lst2 = lst.Where(z => z.Nhom == item.Nhom && z.GroupParent == null && z.GroupGuid != item.GroupGuid && z.IsHeader == false).OrderBy(z => z.STT).ToList();
                    int icount = 1;
                    foreach (var items in lst2)
                    {
                        grlist.Add(new PhanQuyenDanhMucModels
                        {
                            Code = items.Code,
                            GroupGuid = items.GroupGuid,
                            GroupName = items.GroupName,
                            GroupParent = items.GroupParent,
                            Icon = items.Icon,
                            IsHeader = items.IsHeader,
                            KeyLanguage = items.KeyLanguage,
                            LoaiHinh = items.LoaiHinh,
                            MoTa = items.MoTa,
                            Nhom = items.Nhom,
                            RuleType = items.RuleType,
                            UrlLink = items.UrlLink,
                            STT = icount.ToString(),
                            STT2 = items.STT
                        });
                        lst2 = lst.Where(z => z.GroupParent == items.GroupGuid && z.IsHeader == false).OrderBy(z => z.STT).ToList();
                        foreach (var itemss in lst2)
                        {

DFWeb/Views/PhanQuyen/DanhMucPhanQuyen.cshtml
@model List<DF.DBMapping.ModelsExt.PhanQuyen.PhanQuyenDanhMucModels>
@{
    ViewBag.Title = @Html.Raw(Language.GetText("phanquyenchucnang"));
    ViewBag.Title_Function = @Html.Raw(Language.GetText("phanquyenchucnang"));
}
<script type="text/javascript" src="~/Scripts/PhanQuyen/QLPhanQuyen.js"></script>
<style>
    .backgroundisheader{background:#FBEBD7 !important;font-weight:bold;color:red;}
    .backgroudisparent{font-weight:bold;}
</style>
<div class="content dsct">
    <div class="row" style="margin-bottom:10px;">
        <div class="col-xs-5" style="padding-left:0;">
            <div class="form-group">
                <div class="form-group">
                    <input type="text" class="form-control " id="TinhTrangCT" name="TinhTrangCT" style="box-sizing:border-box;width:100%;">
                </div><!-- /.form-group -->
            </div>
        </div>
    </div>
    <div id="grid_DMQuyen"></div>
</div>

<script id="popup_editor" type="text/x-kendo-template">
    <div class="row">
        <div class="col-md-6" style="width:50% !important; box-sizing:border-box">
            <div class="form-group">
                <label>GroupName</label>
                <input type="text" class="form-control" id="GroupName" name="GroupName" data-bind="value:GroupName" required  style="box-sizing:border-box;width:100%;">
            </div><!-- /.form-group -->

        </div><!-- /.col -->
        <div class="col-md-6" style="width:50% !important; box-sizing:border-box">
            <div class="form-group">
                <label>RuleType</label>
                <input type="text" class="form-control" id="RuleType" name="RuleType" data-bind="value:RuleType" required  style="box-sizing:border-box;width:100%;">
            </div><!-- /.form-group -->

        </div><!-- /.col -->
        <div class="col-md-6" style="width:50% !important; box-sizing:border-box">
            <div class="form-group">
                <label>Code</label>
                <div class="input-group" style="width:100%;">
                    <input type="text" class="form-control" name="Code" data-bind="value:Code" id="Code">
                </div>
            </div>
        </div>
        <div class="col-md-6" style="width:50% !important; box-sizing:border-box">
            <div class="form-group">
                <label>UrlLink</label>
                <div class="input-group" style="width:100%;">
                    <input type="text" class="form-control" name="UrlLink"  data-bind="value:UrlLink" id="UrlLink">
                </div>
            </div>
        </div>
        <div class="col-md-6" style="width:50% !important; box-sizing:border-box">
            <div class="form-group">
                <label>Loại Hình</label>
                <input type="text" class="form-control" id="LoaiHinh" name="LoaiHinh" data-bind="value:LoaiHinh" required  style="box-sizing:border-box;width:100%;">
            </div><!-- /.form-group -->

        </div><!-- /.col -->
        <div class="col-md-6" style="box-sizing:border-box">
            <div class="form-group">
                <label>Nhóm</label>
                <input type="text" class="form-control" id="Nhom" name="Nhom" data-bind="value:Nhom" style="box-sizing:border-box;width:100%;">
            </div><!-- /.form-group -->

        </div><!-- /.col -->
        <div class="col-md-6" style="box-sizing:border-box">
            <div class="form-group">
                <label>Parent</label>
                <input type="text" class="form-control" id="Parent" name="Parent" data-bind="value:GroupParent" style="box-sizing:border-box;width:100%;">
            </div><!-- /.form-group -->

        </div><!-- /.col -->
        <div class="col-md-6" style="box-sizing:border-box">
            <div class="form-group">
                <label>Language</label>
                <input type="text" class="form-control" id="Language" name="Language" data-bind="value:KeyLanguage" required style="box-sizing:border-box">
            </div><!-- /.form-group -->

        </div><!-- /.col -->
        <div class="col-md-6" style="box-sizing:border-box">
            <div class="form-group">
                <label>Icon</label>
                <input type="text" class="form-control " id="Icon" name="Icon" data-bind="value:Icon"  style="box-sizing:border-box">
            </div><!-- /.form-group -->

        </div><!-- /.col -->
        <div class="col-md-6" style="box-sizing:border-box">
            <div class="form-group">
                <label>STT</label>
                <input type="text" class="form-control " id="STT" name="STT" data-bind="value:STT2" style="box-sizing:border-box">
            </div><!-- /.form-group -->

        </div><!-- /.col -->
    </div>
</script>

DFWeb/Views/PhanQuyen/Index.cshtml
@{
    ViewBag.Title = @Html.Raw(Language.GetText("qphanquyenchucnang"));
    //Layout = "~/Views/Shared/_LayoutDF.cshtml";
}
<script type="text/javascript" src="~/Scripts/PhanQuyen/PhanQuyen.js"></script>
<link rel="stylesheet" type="text/css" href="~/assets/customcss.css" />

    <script type="text/x-kendo-template" id="tmplaction">
        <div class="text-center">
            <button class="btn btn-xs btn-primary xemchitiet">@Html.Raw(Language.GetText("xemphanquyen"))</button>
        </div>
    </script>
<div class="content dsnv">
    <div id="grid"></div>
</div>
<div id="ChiTietNhanVien"></div>

    <script type="text/x-kendo-template" id="tmplquyen">
        <div>
            <button class="btn btn-primary k-btn pull-right excelsuachuain"><i class="fa fa-floppy-o" aria-hidden="true"></i> @Html.Raw(Language.GetText("luu"))</button>
        </div>
        <div style="clear:both"></div>
        <br />
        <div id="gridquyen"></div>
    </script>
    <script type="text/x-kendo-template" id="tmplchecked">
        # if(IsActive == false) { #
        <input type="checkbox" class="checkquyen" />
        # } #
        # if(IsActive == true) { #
        <input type="checkbox" class="checkquyen" checked="checked"/>
        # } #
    </script>
    <div id="mdlquyen">

    </div>

DFWeb/Views/PhanQuyen/_AddDMQuyen.cshtml
@model DF.DBMapping.ModelsExt.NghiepVu.QuanLyDuAn.CongTrinhResults
@{
    Guid? CongTrinhID = Model == null ? Guid.Empty : Model.CongTrinhID;
    string strDisabled = "";
    string strclasshidden = "hidden";
    string strTrangThai0 = "", strTrangThai1 = "", strTrangThai2 = "", strTrangThai3 = "", strTrangThai4 = "", strTrangThai5 = "selected", strTrangThai6 = "";
    if (Model != null)
    {
        if (Model.DaKyHopDong.Value)
        {
            strDisabled = "";
            strclasshidden = "";
        }
        switch (Model.TinhTrang)
        {
            case 0: strTrangThai0 = "selected"; break;
            case 1: strTrangThai1 = "selected"; break;
            case 2: strTrangThai2 = "selected"; break;
            case 3: strTrangThai3 = "selected"; break;
            case 4: strTrangThai4 = "selected"; break;
            case 5: strTrangThai5 = "selected"; break;
            case 6: strTrangThai6 = "selected"; break;
            default: strTrangThai5 = "selected"; break;
        }
    }
}
<style></style>
<!-- Basic layout-->
<form action="#" class="form-horizontal">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">@Html.Raw(Language.GetText("thongtincongtrinh"))</h5>
        </div>
        <input type="hidden" id="IDCongTrinh" />
        <div class="panel-body">
            <div class="form-group">
                <label class="col-lg-3 control-label">@Html.Raw(Language.GetText("tenquyen")):</label>
                <div class="col-lg-9">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="icon-calendar"></i></span>
                        <input type="text" class="form-control datepicker-format" id="NgayKhoiTao" placeholder=@Html.Raw(Language.GetText("chonngay"))>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label ">RuleType:</label>
                <div class="col-lg-9">
                    <input type="text" required class="form-control validreq" id="TenCongTrinh" placeholder="VietNam">
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label">Code:</label>
                <div class="col-lg-9">
                    <input type="text" class="form-control" id="ChuDauTu" placeholder="DUAFAT">
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">UrlLink:</label>
                <div class="col-lg-9">
                    <input type="text" class="form-control" id="ChuDauTu" placeholder="DUAFAT">
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">@Html.Raw(Language.GetText("nhomquyen")):</label>
                <div class="col-lg-9">
                    <select data-placeholder="Select a state" id="nhomquyen" class="select-clear">
                        <option class="" value=1 @strTrangThai1>@Html.Raw(Language.GetText("dangbaogia"))</option>
                        <option value=2 @strTrangThai2>@Html.Raw(Language.GetText("dabaogia"))</option>
                        <option value=3 @strTrangThai3>@Html.Raw(Language.GetText("chuathicong"))</option>
                        <option value=4 @strTrangThai4>@Html.Raw(Language.GetText("dangthicong"))</option>
                        <option value=5 @strTrangThai5>@Html.Raw(Language.GetText("tamdung"))</option>
                        <option value=6 @strTrangThai6>@Html.Raw(Language.GetText("dahoanthien"))</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">@Html.Raw(Language.GetText("ngaykhoicongdukien")):</label>
                <div class="col-lg-9">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="icon-calendar"></i></span>
                        <input type="text" class="form-control datepicker-format" id="TuNgay" placeholder=@Html.Raw(Language.GetText("chonngay"))>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">@Html.Raw(Language.GetText("ngayhoanthanhdukien")):</label>
                <div class="col-lg-9">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="icon-calendar"></i></span>
                        <input type="text" class="form-control datepicker-format" id="DeNgay" placeholder=@Html.Raw(Language.GetText("chonngay"))>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">@Html.Raw(Language.GetText("trangthai")):</label>
                <div class="col-lg-9">
                    <select data-placeholder="Select a state" id="TrangThai" class="select-clear" @strDisabled>
                        <option class="" value=5 @strTrangThai5>@Html.Raw(Language.GetText("dangbaogia"))</option>
                        <option value=6 @strTrangThai6>@Html.Raw(Language.GetText("dabaogia"))</option>
                        <option value=0 @strTrangThai0>@Html.Raw(Language.GetText("chuathicong"))</option>
                        <option class="@strclasshidden" value=1 @strTrangThai1>@Html.Raw(Language.GetText("dangthicong"))</option>
                        <option class="@strclasshidden" value=2 @strTrangThai2>@Html.Raw(Language.GetText("tamdung"))</option>
                        <option class="@strclasshidden" value=3 @strTrangThai3>@Html.Raw(Language.GetText("dahoanthien"))</option>
                        <option class="@strclasshidden" value=4 @strTrangThai4>@Html.Raw(Language.GetText("daquyettoan"))</option>

                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">@Html.Raw(Language.GetText("diadiem")):</label>
                <div class="col-lg-9">
                    <textarea rows="2" cols="2" id="DiaDiem" class="form-control"></textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-3 control-label">@Html.Raw(Language.GetText("ghichu")):</label>
                <div class="col-lg-9">
                    <textarea rows="3" cols="3" id="GhiChu" class="form-control"></textarea>
                </div>
            </div>
            <div class="form-group" hidden>
                <label class="col-lg-3 control-label">@Html.Raw(Language.GetText("dakyhopdong")):</label>
                <div class="col-lg-9">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" id="KyHopDong" class="control-primary">
                        </label>
                    </div>
                </div>
            </div>

            <div class="text-right">
                <span onclick="saveCongTrinh(); checkFilled();" class="btn btn-success">@Html.Raw(Language.GetText("luu")) <i class="icon-floppy-disk position-right"></i></span>
                <span onclick="detailCongTrinh()" class="btn btn-primary chitietcongtrinh" style="display:none;">@Html.Raw(Language.GetText("chitietduan")) <i class="icon-arrow-right14 position-right"></i></span>
                @if (Model != null)
                {
                    <span onclick="delCongTrinh('@Model.CongTrinhID')" class="btn btn-danger">@Html.Raw(Language.GetText("xoa")) <i class="icon-bin position-right"></i></span>
                }
            </div>
        </div>
    </div>
</form>
<!-- /basic layout -->
<!-- Theme JS files -->



<script type="text/javascript">
    $(".datepicker-format").datepicker({
                    dateFormat: 'dd/mm/yy',
    }).datepicker('setDate', new Date());

    $('.select-clear').select2({
        allowClear: true
    });

    if ('@CongTrinhID' != '00000000-0000-0000-0000-000000000000') {
        $.ajax({
            url: '@Url.Action("ChiTietCongTrinhJson", "QuanLyCongTrinh")',
            method: "POST",
            data: {
                CongTrinhID: '@CongTrinhID'
            },
            datatype: 'json',
            success: function (data) {
                altReturn(data);
                if (data) {
                    LoadChiTietCongTrinh(data.data);
                } else {
                    $("#form_loading").unblock();
                }
            },
            error: function () {
            }
        });
    }

    // Primary
    $(".control-primary").uniform({
        radioClass: 'choice',
        wrapperClass: 'border-primary-600 text-primary-800'
    });

    function LoadChiTietCongTrinh(data) {
        $("#IDCongTrinh").val(data.CongTrinhID);
        $("#NgayKhoiTao").val(data.strNgayTao);
        $("#TenCongTrinh").val(data.TenCongTrinh);
        $("#ChuDauTu").val(data.ChuDauTu);
        $("#TuNgay").val(data.strNgayBatDau);
        $("#DeNgay").val(data.strNgayKetThuc);
        $("#TrangThai").val(data.TinhTrang);
        $("#DiaDiem").val(data.DiaDiem);
        $("#GhiChu").val(data.GhiChu);
        $("#KyHopDong").prop('checked', data.DaKyHopDong);
        $("#KyHopDong").attr("checked", "checked");
    }
    function checkFilled() {
        var inputVal = document.getElementById("TenCongTrinh");
        if (inputVal.value == "") {
            inputVal.style.borderColor = "red";
        }
        else {
            inputVal.style.backgroundColor = "";
        }
    }

</script>

DFWeb/Views/PhanQuyen/_ChiTietPhanQuyenUser.cshtml
@model DF.DBMapping.ModelsExt.PhanQuyen.UserPhanQuyenModels
@{
    ViewBag.Title = @Html.Raw(Language.GetText("phanquyenchucnang"));
    ViewBag.Title_Function = @Html.Raw(Language.GetText("phanquyenchucnang"));
}
<script type="text/javascript" src="~/Scripts/PhanQuyen/QLPhanQuyenChiTiet.js"></script>
<input type="hidden" value="@Model.NhanVienID" id="NhanVienID" />
<input type="hidden" value="@Model.UserID" id="UserID" />
<div class="content dsct" id="content-qlluongkhoan">
    <div class="row" style="margin-bottom:10px;">
        <div class="col-xs-5" style="padding-left:0;">
            <div class="form-group">
                <div class="form-group">
                    <input type="text" class="form-control " id="TinhTrangCT" name="TinhTrangCT" style="box-sizing:border-box;width:100%;">
                </div><!-- /.form-group -->
            </div>
        </div>
    </div>
    <div id="grid_DMQuyen">
        @Html.Partial("~/Views/PhanQuyen/_BangChiTietPhanQyen.cshtml", Model)
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        var loaihopdong = [
            { text: "Đề nghị", value: 1 },
            { text: "web", value: 2 },
        ];
        $("#TinhTrangCT").kendoDropDownList({
            dataSource: loaihopdong,
            dataTextField: "text",
            dataValueField: "value",
            autoBind: true,
            filter: "contains",
            change: function (e) {
                var value = this.value();
                if (value) {
                    SearchPhanQuyen();
                }
            }
        });
        $("#TinhTrangCT").data("kendoDropDownList").value(2);

        function SearchPhanQuyen() {
            ContentWatingOP("content-qlluongkhoan", 1);
            $.ajax({
                url: '@Url.Action("SearchGenPhanQuyenByNhanVien", "PhanQuyen")',
                method: "POST",
                data: {
                    NhanVienID: $("#NhanVienID").val(),
                    UserID: $("#UserID").val(),
                    LoaiHinh: $("#TinhTrangCT").val()
                },
                datatype: 'json',
                success: function (data) {
                    $("#grid_DMQuyen").html(data);
                    $("#content-qlluongkhoan").unblock();
                }, error: function () {
                    $("#content-qlluongkhoan").unblock();
                }
            });
        }
    });
</script>